image: playpauseandstop/docker-python:4.1.0-py39

stages:
  - build
  - deploy

build:pages:
  stage: build
  before_script:
    - poetry install
  script:
    - poetry run mkdocs build
  artifacts:
    paths:
      - "./site"
    expire_in: 1 days

pages:
  stage: deploy
  dependencies:
    - build:pages
  script:
  - mv site public
  artifacts:
    paths:
    - public
    expire_in: 1 days
  only:
  - master
