image: tmaier/docker-compose:18.09
services:
  - docker:19.03-dind

before_script:
  - apk add --no-cache git

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker-compose run pdf_generator

pages:
  stage: deploy
  script:
  - docker-compose run deploy_pages
  - mv site public
  artifacts:
    paths:
    - public
    expire_in: 2 days
  only:
  - master

