image: tmaier/docker-compose:18.09
services:
  - docker:19.03-dind

before_script:
  - apk add --no-cache git

stages:
  - build

build:
  stage: build
  script:
    - docker-compose run pdf_generator
